# pages/f1_drive_query.py

import streamlit as st
from rag import get_vector_store, query_rag_system

vector_store = get_vector_store()

st.set_page_config(
    page_title="❓ Drivers query"
)
st.title("❓ F1 drivers query")
st.caption("Use Gemini's intelligence to get answers based on indexed news.")
st.markdown("---")

st.header("DB query")

# El usuario ingresa su pregunta
user_query = st.text_input(
    "Enter your question about an F1 driver or team:",
    placeholder="What has Hamilton said about Mercedes' engine development for 2026?"
)

if st.button("🚀 RAG query") and user_query:
    st.subheader("Query Result (Generated by Gemini LLM):")

    # Llama a la función del módulo rag.py
    rag_answer = query_rag_system(user_query, vector_store)

    st.markdown(rag_answer)
